image: derekkent/derekkent.com

stages:
  - install
  - build
  - test

install:
  stage: install
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - node_modules/
      - jspm_packages/
  artifacts:
    paths:
      - node_modules/
      - jspm_packages/
  script:
    - npm install
    - jspm install

build:
  stage: build
  dependencies:
    - install
  artifacts:
    paths:
      - dev/
  script:
    - gulp build

lint:
  stage: test
  dependencies:
    - install
  script:
    - gulp lint

unit_tests:
  stage: test
  dependencies:
    - install
    - build
  script:
    - nyc ava
