image: registry.gitlab.com/derekkent/derekkent.com:build

stages:
  - install
  - setup
  - test
  - build
  - release

variables:
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/derekkent/derekkent.com:latest

install dependencies:
  stage: install
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules/
      - jspm_packages/
  artifacts:
    expire_in: 2 days
    paths:
      - node_modules/
      - jspm_packages/
  script:
    - npm install
    - jspm install

setup tests:
  stage: setup
  dependencies:
    - install dependencies
  artifacts:
    expire_in: 2 days
    paths:
      - dev/
  script:
    - gulp build

lint:
  stage: test
  dependencies:
    - install dependencies
  script:
    - gulp lint

unit tests:
  stage: test
  dependencies:
    - install dependencies
    - setup tests
  script:
    - nyc ava

build:
  stage: build
  dependencies:
    - install dependencies
  artifacts:
    expire_in: 2 days
    paths:
      - dist/
  script:
    - gulp dist

release:
  stage: release
  environment: staging
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build --pull -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
